//AddWatchWindowVars Lab 2 & 7
expRemoveAll()
//Variables
expAdd ("CLLLC_Lab.CLLLC_Lab_Enum",getNatural())
expAdd ("CLLLC_pwmSwState.CLLLC_PwmSwState_Enum",getNatural())
expAdd ("CLLLC_powerFlowState.CLLLC_PowerFlowState_Enum",getNatural())
expAdd ("CLLLC_tripFlag.CLLLC_TripFlag_Enum", getNatural())
// following are things that the user can change through the watch window
expAdd ("CLLLC_clearTrip",getNatural())
expAdd ("CLLLC_hfcReceiverTestEnable",getNatural())
expAdd ("CLLLC_hfcReceiverTestRun",getNatural())
expAdd ("CLLLC_hfcReceiverTestActive",getNatural())
expAdd ("CLLLC_hfcReceiverTestMode",getNatural())
expAdd ("CLLLC_hfcReceiverTestSyncEnable",getNatural())
expAdd ("CLLLC_hfcReceiverTestSyncConfigured",getNatural())
expAdd ("CLLLC_hfcReceiverTestReady",getNatural())
expAdd ("CLLLC_hfcReceiverTestInhibit",getNatural())
expAdd ("CLLLC_hfcReceiverTestMinITankModRaw",getNatural())
expAdd ("CLLLC_hfcReceiverTestDuty_pu",getNatural())
expAdd ("CLLLC_hfcReceiverTestPhaseShiftPrimLegs_pu",getNatural())
expAdd ("CLLLC_pwmPeriodRef_pu", getNatural())
expAdd ("CLLLC_pwmDeadBandREDPrimRef_ns",getNatural())
expAdd ("CLLLC_pwmDeadBandFEDPrimRef_ns",getNatural())
expAdd ("CLLLC_pwmDutyPrimRef_pu", getNatural())
expAdd ("CLLLC_pwmDutySecRef_pu", getNatural())
expAdd ("CLLLC_pwmPhaseShiftPrimSecRef_ns",getNatural())
//
expAdd ("CLLLC_vPrimSensed_Volts",getNatural())
expAdd ("CLLLC_vSecSensed_Volts",getNatural())
expAdd ("CLLLC_iPrimSensed_Amps",getNatural())
expAdd ("CLLLC_iSecSensed_Amps",getNatural())
expAdd ("CLLLC_pwmFrequency_Hz", getNatural())
expAdd ("EPwm1Regs.TZFLG",getNatural())
expAdd ("CLLLC_hfcGanFaultGpioLevel",getNatural())
expAdd ("CLLLC_hfcGanFaultActiveLow",getNatural())
expAdd ("CLLLC_hfcGanFaultXbarFlag",getNatural())
expAdd ("CLLLC_epwm1TzFlgDebug",getNatural())
expAdd ("CLLLC_epwm2TzFlgDebug",getNatural())
expAdd ("CLLLC_epwm3TzFlgDebug",getNatural())
expAdd ("CLLLC_epwm1TzOstFlgDebug",getNatural())
expAdd ("CLLLC_epwm2TzOstFlgDebug",getNatural())
expAdd ("CLLLC_epwm3TzOstFlgDebug",getNatural())
expAdd ("CLLLC_epwm1GanFaultOst2Latched",getNatural())
expAdd ("CLLLC_epwm2GanFaultOst2Latched",getNatural())
expAdd ("CLLLC_epwm3GanFaultOst2Latched",getNatural())
